# -*- coding: utf-8 -*-
"""valide_qualidade_dados_pyspark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLMhSYihBNrBloSoFWEB9OOKKpbiFqG5
"""

!pip install pyspark

import pyspark
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, count, when, regexp_extract

spark = SparkSession.builder.getOrCreate()

produtos = spark.read.csv('drive/MyDrive/Spark/Data/produtos.csv', header=True, inferSchema=True)
clientes = spark.read.csv('drive/MyDrive/Spark/Data/clientes.csv', header=True, inferSchema=True)
itens_pedido = spark.read.csv('drive/MyDrive/Spark/Data/itens_pedido.csv', header=True, inferSchema=True)
pedidos = spark.read.csv('drive/MyDrive/Spark/Data/pedidos.csv', header=True, inferSchema=True)

itens_pedido = itens_pedido.withColumn('preco_valido', when(col('preco') > 0, 'Valido').otherwise('Invalido'))

itens_pedido.select('id_pedido','id_produto','preco','preco_valido').show()
itens_pedido.filter(col('preco_valido') == 'Invalido').show()

status_permitidos = ['created', 'aproved', 'delivered','shipped','canceled','invoiced','processing']

pedidos = pedidos.withColumn('status_valido', when(col('status_pedido').isin(status_permitidos), "Valido").otherwise('Invalido'))

pedidos.select('id_pedido','status_pedido','status_valido').show()
pedidos.filter(col('status_valido') == 'Invalido').show()

for coluna in clientes.columns:
  clientes.select(count(col(coluna)).alias(coluna)).show()

for coluna in clientes.columns:
  clientes.select(count(when(col(coluna).isNull(), coluna)).alias(coluna)).show()

n_null_pedidos_df = pedidos.select([count(when(col(c).isNull(), c)).alias(c) for c in pedidos.columns])
n_null_pedidos_df.show()

pedidos_integridade_df = pedidos.join(clientes, pedidos.id_cliente == clientes.id_cliente,'left_anti')
pedidos_integridade_df.select('id_pedido','id_cliente').show()

itens_integriade_df = itens_pedido.join(produtos, itens_pedido.id_produto == produtos.id_produto,'left_anti')
itens_integriade_df.select('id_pedido','id_produto').show()

clientes_validacao_df = clientes.withColumn('cep_valido', when(col('cep_cliente').rlike(r"^\d{5}$"), "Válido").otherwise("Inválido"))
clientes_validacao_df.select('id_cliente','cep_cliente','cep_valido').show()

produtos_validacao_df = produtos.withColumn('id_produo_valido', when(col('id_produto').rlike(r"^[a-f0-9]{32}$"), 'Válido').otherwise('Inválido'))
produtos_validacao_df.select('id_produto','id_produo_valido').show()

if 'email_cliente' in clientes.columns:
  clientes_verifica_email_df = clientes.withColumn('email_valido', when(col('email_cliente').contains('@'), 'Válido').otherwise('Inválido'))
  clientes_verifica_email_df.select('id_cliente','email_cliente','email_valido').show()

spark.stop()